name: Docker Image Build

on:
    workflow_dispatch: {}
    push:
        paths-ignore:
            - '.infra/**'
            - '.github/**'
        branches-ignore:
          - main

jobs:
  argus_builder:
    permissions:
      id-token: write
      contents: read
    uses: chanzuckerberg/github-actions/.github/workflows/argus-docker-build.yaml@heathj/docker-build-runson
    secrets: inherit
    with:
      env: rdev
      images: |
        [
          {
            "name": "backend",
            "context": ".",
            "dockerfile": "Dockerfile",
            "platform": "linux/arm64"
          }
        ]
